# Generated by Django 4.2 on 2024-06-09 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='defoulte_agent.jpg', upload_to='agent')),
                ('score', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('x', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
