# Generated by Django 4.2 on 2024-06-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
