# Generated by Django 4.2 on 2024-06-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='propertieSingel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='property_default.jpg', upload_to='property')),
                ('title', models.CharField(max_length=100)),
                ('rent', models.IntegerField()),
                ('area', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('garages', models.IntegerField()),
                ('category', models.ManyToManyField(to='property.category')),
            ],
        ),
    ]
