# Generated by Django 4.2 on 2024-06-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_category_propertiesingel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='propertieSingel',
            new_name='PropertieSingle',
        ),
    ]
