# Generated by Django 4.2 on 2024-06-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rename_propertiesingel_propertiesingle'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
