# Generated by Django 4.2 on 2024-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_propertie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='category',
            field=models.ManyToManyField(to='property.category'),
        ),
        migrations.AddField(
            model_name='propertie',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='garages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='rent',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PropertieSingle',
        ),
    ]
